### ISSUE TITLE
Make Key more interesting

### ISSUE THREAD

**Issue by A5H73Y** [A5H73Y/Carz#13]
Give the key a description, and a name etc.

**Comment by Gaby-TM** [comment]
```yaml
KEY:  
  MATERIAL: STICK
  GLOW: true
  DISPLAY_NAME: '&a{player}''s &fKey'
  LORE:
  - '' # Empty line
  - '&fYou need a key to start the engine!'
```
